#!/usr/bin/python3


def new_in_list(my_list, idx, element):
    """Replaces an element in a list at a specific position
        without modifying the original list (like in C)

       Args:
        my_list: valide python list
        idx: index of list
        element: data to replace item at idx

       Return:
        A new list or old list if failed
    """
    if idx < 0:
        return (my_list)
    elif idx > (len(my_list) - 1):
        return (my_list)

    new_list = []
    i = 0

    while i < len(my_list):
        if i == idx:
            new_list.append(element)
        else:
            new_list.append(my_list[i])
    return (new_list)                          
